In [1]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (1.5.16)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from kaggle) (2024.2.2)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from kaggle) (4.66.2)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.0.7)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle) (6.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.6)

In [2]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [4]:
!kaggle datasets download -d sudalairajkumar/covid19-in-india

Downloading covid19-in-india.zip to /content
100% 758k/758k [00:00<00:00, 1.19MB/s]
100% 758k/758k [00:00<00:00, 1.19MB/s]

In [6]:
from zipfile import ZipFile
dataset = '/content/covid19-in-india.zip'
with ZipFile(dataset, 'r') as zip:
  zip.extractall()
  print("The dataset is extracted")

The dataset is extracted

In [8]:
import pandas as pd
df = pd.read_csv("/content/covid_vaccine_statewise.csv")
print(df.dtypes)

Updated On                              object
State                                   object
Total Doses Administered               float64
Sessions                               float64
 Sites                                 float64
First Dose Administered                float64
Second Dose Administered               float64
Male (Doses Administered)              float64
Female (Doses Administered)            float64
Transgender (Doses Administered)       float64
 Covaxin (Doses Administered)          float64
CoviShield (Doses Administered)        float64
Sputnik V (Doses Administered)         float64
AEFI                                   float64
18-44 Years (Doses Administered)       float64
45-60 Years (Doses Administered)       float64
60+ Years (Doses Administered)         float64
18-44 Years(Individuals Vaccinated)    float64
45-60 Years(Individuals Vaccinated)    float64
60+ Years(Individuals Vaccinated)      float64
Male(Individuals Vaccinated)           float64
Female(Individuals Vaccinated)         float64
Transgender(Individuals Vaccinated)    float64
Total Individuals Vaccinated           float64
dtype: object

In [9]:
df.describe()

,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),Covaxin (Doses Administered),CoviShield (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
count,7.621000e+03,7.621000e+03,7621.000000,7.621000e+03,7.621000e+03,7.461000e+03,7.461000e+03,7461.000000,7.621000e+03,7.621000e+03,...,1.702000e+03,1.702000e+03,1.702000e+03,3.733000e+03,3.734000e+03,3.734000e+03,1.600000e+02,1.600000e+02,160.000000,5.919000e+03
mean,9.188171e+06,4.792358e+05,2282.872064,7.414415e+06,1.773755e+06,3.620156e+06,3.168416e+06,1162.978019,1.044669e+06,8.126553e+06,...,8.773958e+06,7.442161e+06,5.641605e+06,1.395895e+06,2.916515e+06,2.627444e+06,4.461687e+07,3.951018e+07,12370.543750,4.547842e+06
std,3.746180e+07,1.911511e+06,7275.973730,2.995209e+07,7.570382e+06,1.737938e+07,1.515310e+07,5931.353995,4.452259e+06,3.298414e+07,...,2.660829e+07,2.225999e+07,1.681650e+07,5.501454e+06,9.567607e+06,8.192225e+06,3.950749e+07,3.417684e+07,12485.026753,1.834182e+07
min,7.000000e+00,0.000000e+00,0.000000,7.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,0.000000,0.000000e+00,7.000000e+00,...,2.662400e+04,1.681500e+04,9.994000e+03,1.059000e+03,1.136000e+03,5.580000e+02,2.375700e+04,2.451700e+04,2.000000,7.000000e+00
25%,1.356570e+05,6.004000e+03,69.000000,1.166320e+05,1.283100e+04,5.655500e+04,5.210700e+04,8.000000,0.000000e+00,1.331340e+05,...,4.344842e+05,2.326275e+05,1.285605e+05,5.655400e+04,9.248225e+04,5.615975e+04,5.739350e+06,5.023407e+06,1278.750000,7.427550e+04
50%,8.182020e+05,4.547000e+04,597.000000,6.614590e+05,1.388180e+05,3.897850e+05,3.342380e+05,113.000000,1.185100e+04,7.567360e+05,...,3.095970e+06,2.695938e+06,1.805696e+06,2.947270e+05,8.330395e+05,7.887425e+05,3.716590e+07,3.365402e+07,8007.500000,4.022880e+05
75%,6.625243e+06,3.428690e+05,1708.000000,5.387805e+06,1.166434e+06,2.735777e+06,2.561513e+06,800.000000,7.579300e+05,6.007817e+06,...,7.366241e+06,6.969726e+06,5.294763e+06,9.105160e+05,2.499280e+06,2.337874e+06,7.441663e+07,6.685368e+07,19851.000000,3.501562e+06
max,5.132284e+08,3.501031e+07,73933.000000,4.001504e+08,1.130780e+08,2.701636e+08,2.395186e+08,98275.000000,6.236742e+07,4.468251e+08,...,2.243304e+08,1.667575e+08,1.186927e+08,9.224315e+07,9.096888e+07,6.731098e+07,1.349420e+08,1.156684e+08,46462.000000,2.506569e+08

In [10]:
df[df["State"]=="India"]

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,98111.0,153145.0,24.0,251280.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,11/08/2021,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,12/08/2021,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,13/08/2021,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,14/08/2021,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,15/08/2021,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
import numpy as np
states = np.unique(df["State"])
mh = df[df["State"]=="Maharashtra"]
print(mh["First Dose Administered"].sum())

2784364331.0

In [13]:
for state in states:
  temp = df[df["State"] == state]
  print(state, " --> ", temp["First Dose Administered"].sum())

Andaman and Nicobar Islands  -->  16425854.0
Andhra Pradesh  -->  1232860845.0
Arunachal Pradesh  -->  49004980.0
Assam  -->  585600226.0
Bihar  -->  1470502878.0
Chandigarh  -->  44703105.0
Chhattisgarh  -->  796002902.0
Dadra and Nagar Haveli and Daman and Diu  -->  33595063.0
Delhi  -->  624339473.0
Goa  -->  75991368.0
Gujarat  -->  2131646009.0
Haryana  -->  755798352.0
Himachal Pradesh  -->  316294004.0
India  -->  28262144791.0
Jammu and Kashmir  -->  410101777.0
Jharkhand  -->  603673726.0
Karnataka  -->  1873329968.0
Kerala  -->  1193845072.0
Ladakh  -->  17809249.0
Lakshadweep  -->  4363655.0
Madhya Pradesh  -->  1796604591.0
Maharashtra  -->  2784364331.0
Manipur  -->  67409568.0
Meghalaya  -->  62615974.0
Mizoram  -->  47873077.0
Nagaland  -->  42410766.0
Odisha  -->  1032633168.0
Puducherry  -->  41346858.0
Punjab  -->  584346582.0
Rajasthan  -->  2201044187.0
Sikkim  -->  36980929.0
Tamil Nadu  -->  1288532512.0
Telangana  -->  880320645.0
Tripura  -->  192689726.0
Uttar Pradesh  -->  2788411358.0
Uttarakhand  -->  363191446.0
West Bengal  -->  1796449989.0

In [14]:
first_dose = df[df["Updated On"] == "09/08/2021"]

In [15]:
first_dose[["State", "First Dose Administered"]]

                                         State  First Dose Administered
205                                      India              400150406.0
417                Andaman and Nicobar Islands                 216046.0
629                             Andhra Pradesh               17628583.0
841                          Arunachal Pradesh                 692475.0
1053                                     Assam               10495293.0
1265                                     Bihar               23350171.0
1477                                Chandigarh                 700285.0
1689                              Chhattisgarh                9181482.0
1901  Dadra and Nagar Haveli and Daman and Diu                 584370.0
2113                                     Delhi                7835546.0
2326                                       Goa                1094392.0
2538                                   Gujarat               28101222.0
2750                                   Haryana               10086831.0
2962                          Himachal Pradesh                4249849.0
3174                         Jammu and Kashmir                5318516.0
3386                                 Jharkhand                8382280.0
3598                                 Karnataka               25847691.0
3810                                    Kerala               15670747.0
4022                                    Ladakh                 188699.0
4234                               Lakshadweep                  51156.0
4446                            Madhya Pradesh               29723036.0
4658                               Maharashtra               35040812.0
4870                                   Manipur                1159424.0
5082                                 Meghalaya                 938572.0
5294                                   Mizoram                 654946.0
5506                                  Nagaland                 632120.0
5718                                    Odisha               13954592.0
5930                                Puducherry                 601591.0
6142                                    Punjab                8005636.0
6354                                 Rajasthan               27008606.0
6566                                    Sikkim                 497851.0
6778                                Tamil Nadu               20836674.0
6990                                 Telangana               11649268.0
7202                                   Tripura                2411195.0
7414                             Uttar Pradesh               45932488.0
7626                               Uttarakhand                5070544.0
7838                               West Bengal               23257417.0

In [17]:
first_dose = df[(df["Updated On"] == "09/08/2021") & (df["State"] != "India")]

In [18]:
x = first_dose[["State", "First Dose Administered"]]
x.to_csv("FirstDoseIndia.csv", index=False)

In [23]:
Second_dose=df[(df['Updated On' ]=='09/08/2021') &(df['State'] != 'India')]
x=Second_dose[['State','Second Dose Administered' ]]
x.to_csv('SecondDoseIndia.csv',index=False)

In [24]:
df2 = pd.read_csv("SecondDoseIndia.csv")
df2

                                       State  Second Dose Administered
0                Andaman and Nicobar Islands                   94597.0
1                             Andhra Pradesh                 6214312.0
2                          Arunachal Pradesh                  186619.0
3                                      Assam                 2208577.0
4                                      Bihar                 4484768.0
5                                 Chandigarh                  223534.0
6                               Chhattisgarh                 2587695.0
7   Dadra and Nagar Haveli and Daman and Diu                   80851.0
8                                      Delhi                 3000536.0
9                                        Goa                  302519.0
10                                   Gujarat                 9051153.0
11                                   Haryana                 2923550.0
12                          Himachal Pradesh                 1382592.0
13                         Jammu and Kashmir                 1489826.0
14                                 Jharkhand                 1996014.0
15                                 Karnataka                 7432852.0
16                                    Kerala                 6426984.0
17                                    Ladakh                   70337.0
18                               Lakshadweep                   17139.0
19                            Madhya Pradesh                 5733640.0
20                               Maharashtra                12112554.0
21                                   Manipur                  246694.0
22                                 Meghalaya                  231982.0
23                                   Mizoram                  206773.0
24                                  Nagaland                  159388.0
25                                    Odisha                 4200094.0
26                                Puducherry                  151771.0
27                                    Punjab                 2285629.0
28                                 Rajasthan                 8375056.0
29                                    Sikkim                  151538.0
30                                Tamil Nadu                 4686034.0
31                                 Telangana                 3965624.0
32                                   Tripura                  804099.0
33                             Uttar Pradesh                 8515236.0
34                               Uttarakhand                 1596572.0
35                               West Bengal                 9132961.0

In [25]:
males=df['Male(Individuals Vaccinated)']
print(males.max())

134941971.0

In [26]:
females = df['Female(Individuals Vaccinated)']
females.max()

115668447.0